services:
  - type: web
    name: shoppermart
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ShopperMart.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shoppermart-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11.0
databases:
  - name: shoppermart-db
    databaseName: shoppermart
    user: shopperuser
